parameters:
    catchamonkey_console_logger.console_exception_listener.class:   Catchamonkey\Bundle\ConsoleLoggerBundle\EventListener\ConsoleExceptionListener

services:
    kernel.listener.command_dispatch:
        class: %catchamonkey_console_logger.console_exception_listener.class%
        arguments:
            logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: console.exception }
